# --------------------------------------------------
# Overleaf Base Image (sharelatex/sharelatex-base)
# --------------------------------------------------

ARG TEXLIVE_IMAGE=registry.gitlab.com/islandoftex/images/texlive:TL2022-2022-06-19-04-06
FROM $TEXLIVE_IMAGE as texlive

FROM phusion/baseimage:focal-1.0.0

# Makes sure LuaTex cache is writable
# -----------------------------------
ENV TEXMFVAR=/var/lib/sharelatex/tmp/texmf-var


# Install dependencies
# --------------------
RUN apt-get update \
&&  apt-get install -y \
      build-essential wget net-tools unzip time imagemagick optipng strace nginx git python zlib1g-dev libpcre3-dev \
      qpdf \
      aspell aspell-en aspell-af aspell-am aspell-ar aspell-ar-large aspell-bg aspell-bn aspell-br aspell-ca aspell-cs aspell-cy aspell-da aspell-de aspell-el aspell-eo aspell-es aspell-et aspell-eu-es aspell-fa aspell-fo aspell-fr aspell-ga aspell-gl-minimos aspell-gu aspell-he aspell-hi aspell-hr aspell-hsb aspell-hu aspell-hy aspell-id aspell-is aspell-it aspell-kk aspell-kn aspell-ku aspell-lt aspell-lv aspell-ml aspell-mr aspell-nl aspell-nr aspell-ns  aspell-pa aspell-pl aspell-pt aspell-pt-br aspell-ro aspell-ru aspell-sk aspell-sl aspell-ss aspell-st aspell-sv aspell-tl aspell-tn aspell-ts aspell-uk aspell-uz aspell-xh aspell-zu \
    \
# install Node.JS 16
&&  curl -sSL https://deb.nodesource.com/setup_16.x | bash - \
&&  apt-get install -y nodejs \
    \
&&  rm -rf \
# We are adding a custom nginx config in the main Dockerfile.
      /etc/nginx/nginx.conf \
      /etc/nginx/sites-enabled/default \
      /var/lib/apt/lists/*

# Add envsubst
# ------------
ADD server-ce/vendor/envsubst /usr/bin/envsubst
RUN chmod +x /usr/bin/envsubst

# Install TexLive
# ---------------
ENV PATH "${PATH}:/usr/local/texlive/2022/bin/x86_64-linux"

COPY --from=texlive /usr/local/texlive /usr/local/texlive


# Set up sharelatex user and home directory
# -----------------------------------------
RUN adduser --system --group --home /overleaf --no-create-home sharelatex && \
	mkdir -p /var/lib/sharelatex && \
	chown www-data:www-data /var/lib/sharelatex && \
	mkdir -p /var/log/sharelatex && \
	chown www-data:www-data /var/log/sharelatex && \
	mkdir -p /var/lib/sharelatex/data/template_files && \
	chown www-data:www-data /var/lib/sharelatex/data/template_files
