name: Build and push release to Docker Hub

on:
    workflow_dispatch:
    push:
        branches:
            - main
        tags:
            - '*'
    pull_request:
        branches: [ main ]
        
jobs:
  build:
    if: github.repository_owner == 'LCAS'

    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login LCAS
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: lcas.lincoln.ac.uk
          username: ${{ secrets.LCAS_REGISTRY_PUSHER }}
          password: ${{ secrets.LCAS_REGISTRY_TOKEN }}
  
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta-base
        uses: docker/metadata-action@v5
        with:
          images: lcas.lincoln.ac.uk/lcas/overleaf-base

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker base image
        id: build-and-push-base
        uses: docker/build-push-action@v6
        with:
          context: .
          file: server-ce/Dockerfile-base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta-ce
        uses: docker/metadata-action@v5
        with:
          images: lcas.lincoln.ac.uk/lcas/overleaf

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker CE image
        id: build-and-push-ce
        uses: docker/build-push-action@v6
        with:
          context: .
          file: server-ce/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-ce.outputs.tags }}
          labels: ${{ steps.meta-ce.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1